"""init

Revision ID: 562b4921a676
Revises: 
Create Date: 2022-09-09 10:07:56.376996

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '562b4921a676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('guid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_category_guid'), 'category', ['guid'], unique=False)
    op.create_table(
        'book',
        sa.Column('guid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('categoryId', sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.ForeignKeyConstraint(['categoryId'], ['category.guid'], ),
        sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_book_guid'), 'book', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_guid'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_category_guid'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
